In [4]:
## Diabetes 
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib

data = pd.read_csv("D:/smart decision/Data Preprocessing/Cleaned Datasets/cleaned_diabetic_data.csv")

X = data.drop("readmitted", axis=1)
y = data["readmitted"]

le = LabelEncoder()

for col in X.select_dtypes(include="object").columns:
    X[col] = le.fit_transform(X[col].astype(str))

y = le.fit_transform(y)


selector = SelectKBest(score_func=chi2, k=5)

X = selector.fit_transform(X, y)


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

final_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    min_samples_split=2,
    min_samples_leaf=2,
    random_state=42
)

final_model.fit(X_train, y_train)

y_pred = final_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.5847810706705447


In [7]:
## Saved the model
import joblib

joblib.dump(
    final_model,
    r"D:\smart decision\Final models\diabetic_readmission_model.pkl"
)

loaded_model = joblib.load(
    r"D:\smart decision\Final models\diabetic_readmission_model.pkl"
)

print("Model Saved Successfully!")

Model Saved Successfully!


In [9]:
## Pneumonia Final Model

import pandas as pd
import joblib

from sklearn.feature_selection import SelectKBest, chi2
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


data = pd.read_csv(r"D:\smart decision\Data Preprocessing\Cleaned Datasets\cleaned_clinical_pneumonia_dataset.csv")


X = data.drop("true_label", axis=1)
y = data["true_label"]

le = LabelEncoder()

for col in X.select_dtypes(include="object").columns:
    X[col] = le.fit_transform(X[col].astype(str))

y = le.fit_transform(y)


selector = SelectKBest(score_func=chi2, k=5)
X = selector.fit_transform(X, y)


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)


sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


final_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    min_samples_split=2,
    min_samples_leaf=2,
    random_state=42
)

final_model.fit(X_train, y_train)

y_pred = final_model.predict(X_test)

print("Accuracy :", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Save Model


joblib.dump(
    final_model,
    r"D:\smart decision\Final models\Pneumoia\Pneumonia_model.pkl"
)

loaded_model = joblib.load(
    r"D:\smart decision\Final models\Pneumoia\Pneumonia_model.pkl"
)

print("Pneumonia Model Saved Successfully!")


joblib.dump(
    selector,
    r"D:\smart decision\Final models\Pneumoia\Pneumonia_selector.pkl"
)

joblib.dump(
    sc,
    r"D:\smart decision\Final models\Pneumoia\Pneumonia_scaler.pkl"
)

joblib.dump(
    le,
    r"D:\smart decision\Final models\Pneumoia\Pneumonia_labelencoder.pkl"
)

print("All Pneumonia Files Saved Successfully!")

Accuracy : 0.72
[[ 92  15  28]
 [  7 113   5]
 [ 30  20  65]]
              precision    recall  f1-score   support

           0       0.71      0.68      0.70       135
           1       0.76      0.90      0.83       125
           2       0.66      0.57      0.61       115

    accuracy                           0.72       375
   macro avg       0.71      0.72      0.71       375
weighted avg       0.71      0.72      0.71       375

Pneumonia Model Saved Successfully!
All Pneumonia Files Saved Successfully!


In [1]:
## Length of Stay Final Model

import pandas as pd
import joblib
import numpy as np

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

data = pd.read_csv(r"D:\smart decision\Data Preprocessing\Cleaned Datasets\cleaned_LengthOfStay.csv")

X = data.drop("lengthofstay", axis=1)
y = data["lengthofstay"]

le = LabelEncoder()

for col in X.select_dtypes(include="object").columns:
    X[col] = le.fit_transform(X[col].astype(str))


X_train, X_test, y_train, y_test = train_test_split( X, y,test_size=0.25,random_state=42)


sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


final_model = RandomForestRegressor(
    n_estimators=100,
    max_depth=10,
    min_samples_split=2,
    min_samples_leaf=2,
    random_state=42
)

final_model.fit(X_train, y_train)


y_pred = final_model.predict(X_test)

print("MAE :", mean_absolute_error(y_test, y_pred))
print("MSE :", mean_squared_error(y_test, y_pred))
print("RMSE :", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2 Score :", r2_score(y_test, y_pred))


joblib.dump(
    final_model,
    r"D:\smart decision\Final models\Length of stay\lengthofstay_model.pkl"
)

loaded_model = joblib.load(
    r"D:\smart decision\Final models\Length of stay\lengthofstay_model.pkl"
)

print("Length of Stay Model Saved Successfully!")

print("Saved Successfully!")

MAE : 0.6381967606631963
MSE : 0.7211511070720268
RMSE : 0.8492061628792074
R2 Score : 0.8687058823453968
Length of Stay Model Saved Successfully!
Saved Successfully!


In [7]:
## Hospital Analysis Final Model

import pandas as pd
import joblib

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

data = pd.read_csv(r"D:\smart decision\Data Preprocessing\Cleaned Datasets\cleaned_hospital_data_analysis.csv")


X = data.drop("Outcome", axis=1)
y = data["Outcome"]


le = LabelEncoder()

for col in X.select_dtypes(include="object").columns:
    X[col] = le.fit_transform(X[col].astype(str))

y = le.fit_transform(y)


selector = SelectKBest(score_func=chi2, k=5)

X = selector.fit_transform(X, y)


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)


sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


final_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    min_samples_split=2,
    min_samples_leaf=2,
    random_state=42
)

final_model.fit(X_train, y_train)

y_pred = final_model.predict(X_test)


print("Accuracy :", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

joblib.dump(
    final_model,
    r"D:\smart decision\Final models\hospital_model.pkl"
)

loaded_model = joblib.load(
    r"D:\smart decision\Final models\hospital_model.pkl"
)

print("Hospital Analysis Model Saved Successfully!")


joblib.dump(
    final_model,
    r"D:\smart decision\Final models\hospital_model.pkl"
)

loaded_model = joblib.load(
    r"D:\smart decision\Final models\hospital_model.pkl"
)

print("Hospital Analysis Model Saved Successfully!")

Accuracy : 1.0
[[144   0]
 [  0 102]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       144
           1       1.00      1.00      1.00       102

    accuracy                           1.00       246
   macro avg       1.00      1.00      1.00       246
weighted avg       1.00      1.00      1.00       246

Hospital Analysis Model Saved Successfully!
Hospital Analysis Model Saved Successfully!
