In [4]:
## Diabetes 
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib

data = pd.read_csv("D:/smart decision/Data Preprocessing/Cleaned Datasets/cleaned_diabetic_data.csv")

X = data.drop("readmitted", axis=1)
y = data["readmitted"]

le = LabelEncoder()

for col in X.select_dtypes(include="object").columns:
    X[col] = le.fit_transform(X[col].astype(str))

y = le.fit_transform(y)


selector = SelectKBest(score_func=chi2, k=5)

X = selector.fit_transform(X, y)


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

final_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    min_samples_split=2,
    min_samples_leaf=2,
    random_state=42
)

final_model.fit(X_train, y_train)

y_pred = final_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.5847810706705447


In [7]:
## Saved the model
import joblib

joblib.dump(
    final_model,
    r"D:\smart decision\Final models\diabetic_readmission_model.pkl"
)

loaded_model = joblib.load(
    r"D:\smart decision\Final models\diabetic_readmission_model.pkl"
)

print("Model Saved Successfully!")

Model Saved Successfully!


In [9]:
## Pneumonia Final Model

import pandas as pd
import joblib

from sklearn.feature_selection import SelectKBest, chi2
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


data = pd.read_csv(r"D:\smart decision\Data Preprocessing\Cleaned Datasets\cleaned_clinical_pneumonia_dataset.csv")


X = data.drop("true_label", axis=1)
y = data["true_label"]

le = LabelEncoder()

for col in X.select_dtypes(include="object").columns:
    X[col] = le.fit_transform(X[col].astype(str))

y = le.fit_transform(y)


selector = SelectKBest(score_func=chi2, k=5)
X = selector.fit_transform(X, y)


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)


sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


final_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    min_samples_split=2,
    min_samples_leaf=2,
    random_state=42
)

final_model.fit(X_train, y_train)

y_pred = final_model.predict(X_test)

print("Accuracy :", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Save Model


joblib.dump(
    final_model,
    r"D:\smart decision\Final models\Pneumoia\Pneumonia_model.pkl"
)

loaded_model = joblib.load(
    r"D:\smart decision\Final models\Pneumoia\Pneumonia_model.pkl"
)

print("Pneumonia Model Saved Successfully!")


joblib.dump(
    selector,
    r"D:\smart decision\Final models\Pneumoia\Pneumonia_selector.pkl"
)

joblib.dump(
    sc,
    r"D:\smart decision\Final models\Pneumoia\Pneumonia_scaler.pkl"
)

joblib.dump(
    le,
    r"D:\smart decision\Final models\Pneumoia\Pneumonia_labelencoder.pkl"
)

print("All Pneumonia Files Saved Successfully!")

Accuracy : 0.72
[[ 92  15  28]
 [  7 113   5]
 [ 30  20  65]]
              precision    recall  f1-score   support

           0       0.71      0.68      0.70       135
           1       0.76      0.90      0.83       125
           2       0.66      0.57      0.61       115

    accuracy                           0.72       375
   macro avg       0.71      0.72      0.71       375
weighted avg       0.71      0.72      0.71       375

Pneumonia Model Saved Successfully!
All Pneumonia Files Saved Successfully!


In [ ]:
# Length of Stay

import pandas as pd

# Load Dataset
data = pd.read_csv("D:/smart decision/Data Preprocessing/Cleaned Datasets/cleaned_LengthofStay.csv")

# Features and Target
X = data.drop("lengthofstay", axis=1)
y = data["lengthofstay"]


from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in X.select_dtypes(include='object').columns:
    X[col] = le.fit_transform(X[col].astype(str))

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)


from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators':[50],
    'max_depth':[10],
    'min_samples_split':[2],
    'min_samples_leaf':[1]
}

rf = RandomForestRegressor(random_state=42)

grid = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=3,
    scoring='r2',
    n_jobs=-1
)

grid.fit(X_train,y_train)

print("Best Parameters:",grid.best_params_)
print("Best CV Score:",grid.best_score_)


best_rf = grid.best_estimator_

y_pred = best_rf.predict(X_test)

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("MAE :", mean_absolute_error(y_test,y_pred))
print("MSE :", mean_squared_error(y_test,y_pred))
print("RMSE :", np.sqrt(mean_squared_error(y_test,y_pred)))
print("R2 Score :", r2_score(y_test,y_pred))

In [ ]:
joblib.dump(final_model, "Saved_Models/length_of_stay_model.pkl")
loaded_model = joblib.load("Saved_Models/length_of_stay_model.pkl")

print("Model Saved Successfully!")