In [1]:
## Diabetes
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

data = pd.read_csv("D:/smart decision/Data Preprocessing/Cleaned Datasets/cleaned_diabetic_data.csv")

X = data.drop("readmitted", axis=1)
y = data["readmitted"]

le = LabelEncoder()

for col in X.select_dtypes(include="object").columns:
    X[col] = le.fit_transform(X[col].astype(str))

y = le.fit_transform(y)


selector = SelectKBest(score_func=chi2, k=5)

X = selector.fit_transform(X, y)


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


param_grid = {
    'n_estimators': [50, 100],
    'max_depth': [10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

rf = RandomForestClassifier(random_state=42)

grid = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=3,
    scoring='accuracy',
    n_jobs=-1
)

grid.fit(X_train, y_train)


print("Best Parameters :", grid.best_params_)
print("Best Cross Validation Score :", grid.best_score_)


best_rf = grid.best_estimator_

y_pred = best_rf.predict(X_test)


print("Accuracy :", accuracy_score(y_test, y_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report")
print(classification_report(y_test, y_pred))

Best Parameters : {'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 100}
Best Cross Validation Score : 0.5850715368170621
Accuracy : 0.5847810706705447

Confusion Matrix
[[   41  1132  1676]
 [   33  3416  5469]
 [    8  2246 11421]]

Classification Report
              precision    recall  f1-score   support

           0       0.50      0.01      0.03      2849
           1       0.50      0.38      0.43      8918
           2       0.62      0.84      0.71     13675

    accuracy                           0.58     25442
   macro avg       0.54      0.41      0.39     25442
weighted avg       0.56      0.58      0.54     25442



In [3]:
## Pnemonia
import pandas as pd
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split


data = pd.read_csv("D:/smart decision/Data Preprocessing/Cleaned Datasets/cleaned_clinical_pneumonia_dataset.csv")

X = data.drop("true_label", axis=1)
y = data["true_label"]

le = LabelEncoder()

for col in X.select_dtypes(include='object').columns:
    X[col] = le.fit_transform(X[col].astype(str))

y = le.fit_transform(y)

## feature selection

selector = SelectKBest(score_func=chi2, k=5)
X = selector.fit_transform(X, y)

X_train, X_test, y_train, y_test = train_test_split( X, y,test_size=0.25, random_state=42)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators':[50,100],
    'max_depth':[10,20],
    'min_samples_split':[2,5],
    'min_samples_leaf':[1,2]
}

rf = RandomForestClassifier(random_state=42)

grid = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=3,
    scoring='accuracy',
    n_jobs=-1
)

grid.fit(X_train,y_train)

print("Best Parameters:",grid.best_params_)
print("Best CV Score:",grid.best_score_)


best_rf = grid.best_estimator_

y_pred = best_rf.predict(X_test)


from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

print("Accuracy:",accuracy_score(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test,y_pred))

Best Parameters: {'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 100}
Best CV Score: 0.6657777777777777
Accuracy: 0.72
[[ 92  15  28]
 [  7 113   5]
 [ 30  20  65]]
              precision    recall  f1-score   support

           0       0.71      0.68      0.70       135
           1       0.76      0.90      0.83       125
           2       0.66      0.57      0.61       115

    accuracy                           0.72       375
   macro avg       0.71      0.72      0.71       375
weighted avg       0.71      0.72      0.71       375



In [5]:
# Length of Stay

import pandas as pd

# Load Dataset
data = pd.read_csv("D:/smart decision/Data Preprocessing/Cleaned Datasets/cleaned_LengthofStay.csv")

# Features and Target
X = data.drop("lengthofstay", axis=1)
y = data["lengthofstay"]


from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in X.select_dtypes(include='object').columns:
    X[col] = le.fit_transform(X[col].astype(str))

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)


from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators':[50],
    'max_depth':[10],
    'min_samples_split':[2],
    'min_samples_leaf':[1]
}

rf = RandomForestRegressor(random_state=42)

grid = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=3,
    scoring='r2',
    n_jobs=-1
)

grid.fit(X_train,y_train)

print("Best Parameters:",grid.best_params_)
print("Best CV Score:",grid.best_score_)


best_rf = grid.best_estimator_

y_pred = best_rf.predict(X_test)

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("MAE :", mean_absolute_error(y_test,y_pred))
print("MSE :", mean_squared_error(y_test,y_pred))
print("RMSE :", np.sqrt(mean_squared_error(y_test,y_pred)))
print("R2 Score :", r2_score(y_test,y_pred))

Best Parameters: {'max_depth': 10, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 50}
Best CV Score: 0.8629584558966364
MAE : 0.6390232960341801
MSE : 0.7218161566669162
RMSE : 0.8495976439862085
R2 Score : 0.868584802173847


In [6]:

# HOSPITAL ANALYSIS - GRIDSEARCHCV


import pandas as pd

# Load Dataset
data = pd.read_csv("D:/smart decision/Data Preprocessing/Cleaned Datasets/cleaned_hospital_data_analysis.csv")

X = data.drop("Outcome", axis=1)    
y = data["Outcome"]                   

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in X.select_dtypes(include='object').columns:
    X[col] = le.fit_transform(X[col].astype(str))

y = le.fit_transform(y)

from sklearn.feature_selection import SelectKBest, chi2

selector = SelectKBest(score_func=chi2, k=5)
X = selector.fit_transform(X, y)


from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [50, 100],
    'max_depth': [10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

rf = RandomForestClassifier(random_state=42)

grid = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=3,
    scoring='accuracy',
    n_jobs=-1
)

grid.fit(X_train, y_train)

print("Best Parameters:", grid.best_params_)
print("Best Cross Validation Score:", grid.best_score_)

best_rf = grid.best_estimator_

y_pred = best_rf.predict(X_test)


from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report")
print(classification_report(y_test, y_pred))

Best Parameters: {'max_depth': 10, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 50}
Best Cross Validation Score: 1.0
Accuracy: 1.0

Confusion Matrix
[[144   0]
 [  0 102]]

Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       144
           1       1.00      1.00      1.00       102

    accuracy                           1.00       246
   macro avg       1.00      1.00      1.00       246
weighted avg       1.00      1.00      1.00       246

